# Generated by Django 5.1.5 on 2025-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_email_order_guest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rewards_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
