# Generated by Django 5.1.5 on 2025-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
