# Generated by Django 5.1.5 on 2025-04-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_percentage',
        ),
    ]
