# Generated by Django 5.1.5 on 2025-04-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_tip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_ticket_printed',
            field=models.BooleanField(default=False),
        ),
    ]
