# Generated by Django 5.1.5 on 2025-03-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='connection_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online Payment'), ('terminal', 'Terminal Payment')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='terminal_reader_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
