# Generated by Django 5.1.5 on 2025-03-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_connection_token_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='connection_token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='terminal_reader_id',
        ),
    ]
