# Generated by Django 5.1.5 on 2025-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripelocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeLocation',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
