# Generated by Django 5.1.5 on 2025-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_status_paymenttransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transactions_json',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='charge_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit Card'), ('split', 'Split Payment'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit Card'), ('other', 'Other')], max_length=50),
        ),
    ]
