# Generated by Django 5.1.5 on 2025-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
    ]
