# Generated by Django 5.1.2 on 2025-02-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardwareLog',
        ),
    ]
