# Generated by Django 5.1.5 on 2025-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_discount_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
