# Generated by Django 5.1.5 on 2025-03-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_pos_user_customuser_is_website_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('customer', 'Website Customer')], default='cashier', max_length=20),
        ),
    ]
