# Generated by Django 5.1.5 on 2025-04-10 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.rewardsprofile'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.rewardsprofile'),
        ),
    ]
